@Annie_API_HostAddress = http://localhost:7000

POST {{Annie_API_HostAddress}}/api/sessions
Content-Type: application/json

{
  "name": "Test Session",
  "starttime": "2024-06-01T10:00:00Z",
  "capacity": 10,
  "instructors": ["Me"]
}

###

GET {{Annie_API_HostAddress}}/api/sessions

###

@id=1
GET {{Annie_API_HostAddress}}/api/sessions/{{id}}

###

POST {{Annie_API_HostAddress}}/api/sessions
Content-Type: application/json

{
  "name": "Test Session2",
  "starttime": "2024-06-01T10:00:00Z",
  "capacity": 20,
  "instructors": ["You"]
}

###
POST {{Annie_API_HostAddress}}/api/Users
Content-Type: application/json
{
  "id": "2",
  "name": "Annie",
  "email": "baba",
  "password": "bobo"
}

###

POST {{Annie_API_HostAddress}}/api/register
Content-Type: application/json

{
  "name": "Annie",
  "email": "bobo",
  "password": "bobo"
}

###

POST {{Annie_API_HostAddress}}/api/login
Content-Type: application/json

{
  "email": "bobo",
  "password": "baba"
}

###
