@Annie_API_HostAddress = http://localhost:7000

// USER REQUESTS
POST {{Annie_API_HostAddress}}/api/Users
Content-Type: application/json
{
  "id": "2",
  "name": "Annie",
  "email": "baba",
  "password": "bobo"
}

###

POST {{Annie_API_HostAddress}}/api/register
Content-Type: application/json

{
  "name": "Annie",
  "email": "agibahjks",
  "password": "bobo"
}

###

POST {{Annie_API_HostAddress}}/api/login
Content-Type: application/json

{
  "email": "bobo",
  "password": "baba"
}

###
// SESSION REQUESTS
POST {{Annie_API_HostAddress}}/api/sessions
Content-Type: application/json

{
  "name": "Test Session2",
  "starttime": "2026-06-01T10:00:00Z",
  "capacity": 20,
  "instructors": "You"
}
###

// BOOKING REQUESTS
POST {{Annie_API_HostAddress}}/api/bookings
Content-Type: application/json

{
  "userId": "2",
  "sessionId": "2"
}

###
